[package]
name = "transcript"
version = "0.1.0"
authors = ["kilic <kiliconu@itu.edu.tr>"]
edition = "2021"

[dependencies]
halo2 = { package = "halo2_proofs", git = "https://github.com/appliedzkp/halo2.git" }
rand = "0.8"
group = "0.11"
subtle = { version = "2.3", default-features = false }
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"

[dev-dependencies]
rand_core = { version = "0.6", default-features = false }
